apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeappdep
  labels:
    app: nodeapp
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: ifeanyisam/nodeapp:v1.1 
          ports:
            - containerPort: 3000
